<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDyXB5ST\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDyXB5ST/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDyXB5ST.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDyXB5ST\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDyXB5ST\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DyXB5ST',
    'container.build_id' => '7efd391e',
    'container.build_time' => 1519135344,
));
